### PR TITLE
Add testing

### PR DESCRIPTION
**Pull request by nihonjinrxs**
Add Jest-based tests to this repo and setup Travis CI.

### CODE REVIEW

**Comment by nihonjinrxs** [comment]
@teetow - This is a work in progress, hence the draft PR. I've added tests for all of `shrines.ts` and 3 out of 4 of the files in `./lib`.

I'll try to get the `rando` file tested later today, then start trying to piece together some good testing for the components. The test files on those each have a single test that just confirms that you the component renders without generating an error.

I also noticed that there were some errors when building the project (`yarn build`). I'll try to fix that once there are good tests in place.

**Comment by teetow** [comment]
Fantastic work! I hope my last commit didn't wreak complete havoc on your tests =/  The rewrite of `time.js` in particular will probably need some more TLC, but it's great to get test coverage underway.

**Comment by nihonjinrxs** [comment]
Should be fine -- I commented there -- so I'll pull master here when I get a sec, and update those tests for `lib/time.ts`.

**Comment by nihonjinrxs** [comment]
Closing this PR in favor of #5

**Pull request closed without merging**
